kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: minix-chain-0
  namespace: pre
  labels:
    app: minix-chain-0
    network-mini-pre: minichain-pre
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"minix-chain-0"},"name":"minix-chain-0","namespace":"pre"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"minix-chain-0"}},"serviceName":"minix-chain-0","template":{"metadata":{"creationTimestamp":null,"labels":{"app":"minix-chain-0"}},"spec":{"containers":[{"args":["/usr/local/bin/minix","--chain=/etc/config/chain_spec.json","--keystore-path=/etc/config/auth0","--base-path=auth0","--discover-local","--ws-port=9999","--rpc-port=8888","--rpc-cors=all","--validator"],"image":"docker.io/comingweb3/minix-chain-pre:3","imagePullPolicy":"Always","name":"minix-chain-0","ports":[{"containerPort":8888,"name":"rpc","protocol":"TCP"},{"containerPort":9999,"name":"websocket","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/auth0","name":"minix-data"},{"mountPath":"/etc/config/chain_spec.json","name":"chain-spec","subPath":"chain_spec.json"},{"mountPath":"/etc/config/auth0","name":"keystore"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"initContainers":[{"args":["/bin/sh","-c","echo
      'init minix
      chain'"],"image":"busybox:1.28","imagePullPolicy":"Always","name":"install","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/work-dir","name":"chain-data"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"chain-data"},{"configMap":{"defaultMode":420,"name":"chain-config"},"name":"chain-spec"},{"name":"keystore","secret":{"defaultMode":420,"secretName":"auth0"}}]}},"volumeClaimTemplates":[{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"creationTimestamp":null,"name":"minix-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minix-chain-0
      network-mini-pre: minichain-pre
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minix-chain-0
        network-mini-pre: minichain-pre
    spec:
      volumes:
        - name: chain-data
          emptyDir: {}
        - name: chain-spec
          configMap:
            name: chain-config
            defaultMode: 420
        - name: keystore
          secret:
            secretName: auth0
            defaultMode: 420
      initContainers:
        - name: install
          image: 'busybox:1.28'
          args:
            - /bin/sh
            - '-c'
            - echo 'init minix chain'
          resources: {}
          volumeMounts:
            - name: chain-data
              mountPath: /work-dir
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - name: minix-chain-0
          image: 'docker.io/comingweb3/minix-chain-pre:3'
          args:
            - /usr/local/bin/minix
            - '--chain=/etc/config/chain_spec.json'
            - '--keystore-path=/etc/config/auth0'
            - '--base-path=auth0'
            - '--discover-local'
            - '--ws-port=9999'
            - '--rpc-port=8888'
            - '--rpc-cors=all'
            - '--validator'
          ports:
            - name: rpc
              containerPort: 8888
              protocol: TCP
            - name: websocket
              containerPort: 9999
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: minix-data
              mountPath: /auth0
            - name: chain-spec
              mountPath: /etc/config/chain_spec.json
              subPath: chain_spec.json
            - name: keystore
              mountPath: /etc/config/auth0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: minix-data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: minix-chain-0
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
