kind: Deployment
apiVersion: apps/v1
metadata:
  name: minix-chain
  namespace: prod
  labels:
    app: minix-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minix-chain
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minix-chain
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: chain-data
          emptyDir: {}
        - name: chain-spec
          configMap:
            name: chain-config
            defaultMode: 420
      initContainers:
        - name: install
          image: 'busybox:1.28'
          args:
            - /bin/sh
            - '-c'
            - >-
              echo 'init minix chain'
          resources: {}
          volumeMounts:
            - name: chain-data
              mountPath: /work-dir
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - name: minix-chain
          image: docker.io/comingweb3/minix-chain:12
          args:
            - '--chain=/etc/config/chain_spec.json'
            - '--validator'
          ports:
            - name: rpc
              containerPort: 8888
              protocol: TCP
            - name: websocket
              containerPort: 9999
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: chain-data
              mountPath: /data
            - name: chain-spec
              mountPath: /etc/config/chain_spec.json
              subPath: chain_spec.json
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600